[project]
name = "interactive-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=39.0.0",
    "questionary>=2.1.1",
]
